
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "dirfuzz/pkg/engine"


)

var tests = []testing.InternalTest{

	{"TestSanitizeHeaderToken", _test.TestSanitizeHeaderToken},

	{"TestBuildRequestSetsAcceptEncodingIdentity", _test.TestBuildRequestSetsAcceptEncodingIdentity},

	{"TestExecuteRequestWithRetryDoesNotLogCanceledContextAsNetworkError", _test.TestExecuteRequestWithRetryDoesNotLogCanceledContextAsNetworkError},

	{"TestCheckRecursiveWildcardFailsClosedOnEmptyResponse", _test.TestCheckRecursiveWildcardFailsClosedOnEmptyResponse},

	{"TestCheckRecursiveWildcardDoesNotTreat403AsWildcard", _test.TestCheckRecursiveWildcardDoesNotTreat403AsWildcard},

	{"TestRecursiveMirrorReferencePaths", _test.TestRecursiveMirrorReferencePaths},

	{"TestRecursiveMirrorDetectionSuppressesRepeatedResponses", _test.TestRecursiveMirrorDetectionSuppressesRepeatedResponses},

	{"TestShouldPruneRecursiveBranchSkipsFontDirectory", _test.TestShouldPruneRecursiveBranchSkipsFontDirectory},

	{"TestShouldPruneRecursiveBranchKeepsInterestingDirectoryListing", _test.TestShouldPruneRecursiveBranchKeepsInterestingDirectoryListing},

	{"TestShouldPruneRecursiveBranchKeepsAPIRoutes", _test.TestShouldPruneRecursiveBranchKeepsAPIRoutes},

	{"TestClassify403", _test.TestClassify403},

	{"TestSimhashBodyIsStable", _test.TestSimhashBodyIsStable},

	{"TestExecuteAuthMatrixRequestsDetectsPrivilegeEscalation", _test.TestExecuteAuthMatrixRequestsDetectsPrivilegeEscalation},

	{"TestLiveResponseHarvestQueuesDiscoveredEndpointsFromScanResults", _test.TestLiveResponseHarvestQueuesDiscoveredEndpointsFromScanResults},

	{"TestDiscoverParamHitsBisectsHiddenParameters", _test.TestDiscoverParamHitsBisectsHiddenParameters},

	{"TestSimhashSoft404Clustering", _test.TestSimhashSoft404Clustering},

	{"TestSpiderChildJobIncrementsDepth", _test.TestSpiderChildJobIncrementsDepth},

	{"TestAutoCalibrate", _test.TestAutoCalibrate},

	{"TestAutoCalibrateUsesNormalizedBodySize", _test.TestAutoCalibrateUsesNormalizedBodySize},

	{"TestAutoCalibrateUsesPayloadPlaceholderInBaseURL", _test.TestAutoCalibrateUsesPayloadPlaceholderInBaseURL},

	{"TestIsSameSpiderScopeHostIgnoresPort", _test.TestIsSameSpiderScopeHostIgnoresPort},

	{"TestSetRPSUpdatesLimiterBurst", _test.TestSetRPSUpdatesLimiterBurst},

	{"TestLoadResumeStateRestoresBloomFilter", _test.TestLoadResumeStateRestoresBloomFilter},

	{"TestChangeWordlistConcurrency", _test.TestChangeWordlistConcurrency},

	{"TestVerbTamperHeaders", _test.TestVerbTamperHeaders},

	{"TestWorkerVerbTamperHonorsManualOverrideHeader", _test.TestWorkerVerbTamperHonorsManualOverrideHeader},

	{"TestHarvestEndpointsFull", _test.TestHarvestEndpointsFull},

	{"TestHarvestEndpointsModes", _test.TestHarvestEndpointsModes},

	{"TestHarvestResponseFollowsDiscoveredAPIEndpoints", _test.TestHarvestResponseFollowsDiscoveredAPIEndpoints},

	{"TestHarvestResponseHonorsDepthLimit", _test.TestHarvestResponseHonorsDepthLimit},

	{"TestHarvestResponseNormalizesQueryValuesAndDedupeKeys", _test.TestHarvestResponseNormalizesQueryValuesAndDedupeKeys},

	{"TestHarvestResponseAppliesHintedParamToOwningEndpoint", _test.TestHarvestResponseAppliesHintedParamToOwningEndpoint},

	{"TestHarvestResponseFollowUpParsesUnauthorizedBodiesForParamHints", _test.TestHarvestResponseFollowUpParsesUnauthorizedBodiesForParamHints},

	{"TestHarvestResponseDoesNotTurnHTMLFormsIntoHarvestedQueryStrings", _test.TestHarvestResponseDoesNotTurnHTMLFormsIntoHarvestedQueryStrings},

	{"TestHarvestResponseDoesNotTurnStaticAssetsIntoHarvestedQueryStrings", _test.TestHarvestResponseDoesNotTurnStaticAssetsIntoHarvestedQueryStrings},

	{"TestFuzzParamsIncludesRawWhenSaveRawEnabled", _test.TestFuzzParamsIncludesRawWhenSaveRawEnabled},

	{"TestShouldQueueParamFuzzSkipsRedirects", _test.TestShouldQueueParamFuzzSkipsRedirects},

	{"TestFuzzParamsWithoutWordlistReturnsNoHits", _test.TestFuzzParamsWithoutWordlistReturnsNoHits},

	{"TestFuzzParamsUsesConfiguredWordlist", _test.TestFuzzParamsUsesConfiguredWordlist},

	{"TestQueueParamFuzzRequiresConfiguredWordlist", _test.TestQueueParamFuzzRequiresConfiguredWordlist},

	{"TestQueueParamFuzzUsesFinalRedirectURLAsTaskTarget", _test.TestQueueParamFuzzUsesFinalRedirectURLAsTaskTarget},

	{"TestParamTaskIdentityIgnoresQueryValues", _test.TestParamTaskIdentityIgnoresQueryValues},

	{"TestEnqueueParamTaskDedupesByQueryKeysNotValues", _test.TestEnqueueParamTaskDedupesByQueryKeysNotValues},

	{"TestParamHitIdentityDedupesEquivalentProbeURLs", _test.TestParamHitIdentityDedupesEquivalentProbeURLs},

	{"TestMarkParamHitSeenSuppressesDuplicateProbeResults", _test.TestMarkParamHitSeenSuppressesDuplicateProbeResults},

	{"TestLearnedParamsAreQueuedForKnownPHPTargets", _test.TestLearnedParamsAreQueuedForKnownPHPTargets},

	{"TestFuzzParamsMergesResponseHintsIntoConfiguredWordlist", _test.TestFuzzParamsMergesResponseHintsIntoConfiguredWordlist},

	{"TestFuzzParamsUsesNumericProbeValuesForIdentifierParams", _test.TestFuzzParamsUsesNumericProbeValuesForIdentifierParams},

	{"TestFuzzParamsSuppressesNotFoundProbeTransitions", _test.TestFuzzParamsSuppressesNotFoundProbeTransitions},

	{"TestExtractParamHintsFromTextSkipsCommonStopwords", _test.TestExtractParamHintsFromTextSkipsCommonStopwords},

	{"TestFuzzParamsSuppressesGenericQueryStringChanges", _test.TestFuzzParamsSuppressesGenericQueryStringChanges},

	{"TestExtractParamHintsFromHTMLFormsAndLinks", _test.TestExtractParamHintsFromHTMLFormsAndLinks},

	{"TestCanonicalPassiveHarvestCandidate", _test.TestCanonicalPassiveHarvestCandidate},

	{"TestPassiveHarvestingQueuesAndTimesOutSlowSource", _test.TestPassiveHarvestingQueuesAndTimesOutSlowSource},

	{"TestPluginMatcher", _test.TestPluginMatcher},

	{"TestPluginMutator", _test.TestPluginMutator},

	{"TestPluginMatcherError", _test.TestPluginMatcherError},

	{"TestPluginMutatorError", _test.TestPluginMutatorError},

	{"TestRunActiveTemplateTimesOut", _test.TestRunActiveTemplateTimesOut},

	{"TestHTTPLibBlocksPrivateTargetWhenNotAllowed", _test.TestHTTPLibBlocksPrivateTargetWhenNotAllowed},

	{"TestHTTPLibAllowsPrivateTargetWhenEnabled", _test.TestHTTPLibAllowsPrivateTargetWhenEnabled},

	{"TestPluginMatcherFallsBackWhenPoolIsBusy", _test.TestPluginMatcherFallsBackWhenPoolIsBusy},

	{"TestEvasionScoreboardRanking", _test.TestEvasionScoreboardRanking},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "dirfuzz"
	testdeps.ImportPath = "dirfuzz/pkg/engine"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

